# Site settings
title: gLab
email: 
description: > # this means to ignore newlines until "baseurl:"
  Geometric structures lab
baseurl: "" # the subpath of your site, e.g. /blog/
iconurl: "/images/contact.png"
icondesc: "Contact structure"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  g-s-lab

# Build settings
markdown: kramdown
